export const CREATE_CLIENT = "CREATE_CLIENT";
export const RETRIEVE_CLIENTS = "RETRIEVE_CLIENTS";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const DELETE_ALL_CLIENTS = "DELETE_ALL_CLIENTS";